### PR TITLE
Typescript typing definitions

### LINKED ISSUE #16: Create TypeScript typings
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

### PR DESCRIPTION
**Pull request by lsmoura**
Fixes #16

### CODE REVIEW

**Comment by tommasoverola** [comment]
Is it possible to add an example of usage ?

**Comment by lsmoura** [comment]
Sure! You really just need to import stuff and start to use it. The IDE should give you hints of usage and if you try to pass something around that is wrong, the IDE will yell at you (or the output of the `tsc` command).

This code, for example, is valid:

```typescript
import preact from 'preact';
import {preact as preactRendererGenerator, PreactType} from 'jsx-pragmatic';

const preactOptions: PreactType = {
  h: (foo: any) => {
    console.log('hello preact', foo);
  },
};

const preactRenderer = preactRendererGenerator({Preact: preact});
const preactRenderer2 = preactRendererGenerator({Preact: preact});

preactRenderer('foobar123');
preactRenderer2('foobar123');
```

If you run the command `tsc` on that source, you'll get no output on console and the corresponding `js` file will be:

```javascript
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var preact_1 = __importDefault(require("preact"));
var jsx_pragmatic_1 = require("jsx-pragmatic");
var preactOptions = {
    h: function (foo) {
        console.log('hello preact', foo);
    },
};
var preactRenderer = jsx_pragmatic_1.preact({ Preact: preact_1.default });
var preactRenderer2 = jsx_pragmatic_1.preact({ Preact: preact_1.default });
preactRenderer('foobar123');
preactRenderer2('foobar123');
```

**Comment by lsmoura** [comment]
@tommasoverola Let me know if you need any more clarifications.

Just remembered: Since this file will be inside `jsx-pragmatic` package, anyone adding this as a dependency that uses typescript, will automatically have your types available. No need to search for other dependencies (I often think: "this project has no typing instructions, I wonder if the package `@types/foobar123` exists?", only to go try and... the package is not there).

Whenever people are running a node/react project and "trimming the fat" (as they should, with some command like `find . -type f -name '*.ts' -delete`), the typing instructions will be stripped out automatically.

**Comment by tommasoverola** [comment]
@lsmoura 
First of all thanks for answer me :) 
Actually i'm trying to use `jsx-pragmatic` with react and typescript, this is a simple code snippet, could you pls help me to understand why this still not work ?. maybe there is something that i'm doing wrong

```javascript
/* @jsx node */
import React from 'react'
import {react, ReactType} from 'jsx-pragmatic'

const reactOptions: ReactType = {
  createElement: (props: any) => {
    return <div>Hì</div>
  }
}

const HelloComponent = react({React: reactOptions})

export default HelloComponent
```

**Comment by lsmoura** [comment]
@tommasoverola Take a look at my changes:

```typescript
/* @jsx node */
import {node, react, ReactType} from 'jsx-pragmatic'

const reactOptions: ReactType = {
  createElement: (props: any) => {
    return <div>Hì</div>
  }
}

const HelloComponent = react({React: reactOptions})

export default HelloComponent
```

and the output:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* @jsx node */
var jsx_pragmatic_1 = require("jsx-pragmatic");
var reactOptions = {
    createElement: function (props) {
        return jsx_pragmatic_1.node("div", null, "H\u00EC");
    }
};
var HelloComponent = jsx_pragmatic_1.react({ React: reactOptions });
exports.default = HelloComponent;
```

First problem: You declared that you wanted to handle jsx with `node`, but there was no such function. You needed to import it.

Second "problem": You don't really need "React", since you're using `node`, as you requested on the first line.

Third "possible problem": you need to have `"jsx": "react"` on your `tsconfig.json` file.

Note that your jsx was converted to `...node(...);`.

**Comment by lsmoura** [comment]
Not entirely sure if any of that is actually "useful" or not. Better to stick with the suggestions on the readme. I've just added the typechecking.

**Pull request closed without merging**
